class_name CycloneCodec

# Generated by cyclonec. Do not edit.
#
# Sources:
#     device_state.gd
#     every_primitive.gd
#     no_codecs.gd
#     no_fields_joined.gd
#     player.gd
#     player_info.gd
#     team.gd
#     telemetry.gd
#
# This file is self-contained: it carries the Cyclone runtime (Writer,
# Reader, DecodeError, Limits) as well as every codec, nested inside this
# file's own class_name (CycloneCodec), reachable project-wide with
# nothing to preload. Add it to your project (cyclone.codec.gd) and it compiles.
#
# A nested model field must already hold an instance (`= PlayerInfo.new()`) before
# decode fills its routed fields in place.

# ======================================================================
# Cyclone runtime - RFC-0002, carried verbatim.
#
# Not generated from your models: this block is identical in every file
# cyclonec writes. It is here so the file is self-contained.
# ======================================================================

# A byte stream that does not satisfy the Cyclone Specification.
#
# GDScript has no exceptions, so every `decode` below returns a
# DecodeError (or null, on success) instead of throwing one - see this
# module's file-level docs.
class DecodeError:
	var kind: String = ""
	var needed: int = 0
	var remaining: int = 0
	var invalid_byte: int = 0
	var length: int = 0
	var limit: int = 0

	func message() -> String:
		match kind:
			"unexpected_eof":
				return "unexpected eof: needed %d bytes, %d remaining" % [needed, remaining]
			"invalid_bool":
				return "invalid bool: 0x%02X is neither 0x00 nor 0x01" % invalid_byte
			"invalid_utf8":
				return "invalid utf-8 in string"
			"length_overflow":
				return "length overflow: length %d exceeds limit %d" % [length, limit]
			_:
				return "cyclone: decode error"

# Allocation guards applied while decoding (RFC-0002 §4).
#
# A u32 length can claim up to 4 GiB, so a decoder that allocates straight
# from an untrusted one is a denial-of-service target. These are not part
# of the wire format: two peers with different limits may disagree about a
# byte stream, and neither is wrong.
class Limits:
	var max_string_len: int = 0xFFFFFFFF
	var max_bytes_len: int = 0xFFFFFFFF
	# Largest accepted element count of an Array<T> (RFC-0002 §6). A u32
	# count can claim up to 4 GiB of elements before a single one is even
	# read, so this guards allocation the same way max_string_len/
	# max_bytes_len do.
	var max_array_count: int = 0xFFFFFFFF

# Writer appends Cyclone-encoded values to a growable buffer.
#
# Every multi-byte value is Little Endian, with no padding, no alignment
# and no metadata between values.
class Writer:
	var buf: PackedByteArray = PackedByteArray()

	func bytes() -> PackedByteArray:
		return buf

	func size() -> int:
		return buf.size()

	func write_bool(value: bool) -> void:
		write_u8(1 if value else 0)

	func write_i8(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 1)
		buf.encode_s8(start, value)

	func write_u8(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 1)
		buf.encode_u8(start, value)

	func write_i16(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 2)
		buf.encode_s16(start, value)

	func write_u16(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 2)
		buf.encode_u16(start, value)

	func write_i32(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 4)
		buf.encode_s32(start, value)

	func write_u32(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 4)
		buf.encode_u32(start, value)

	# u64/i64 share one 64-bit two's-complement word either way: GDScript's
	# `int` is itself a 64-bit signed value, so a `u64` field whose top bit
	# is set reads back as a negative GDScript `int` - the wire bytes are
	# still exactly right (h.md's own rule: no native type decides the
	# wire format). Interpreting that bit pattern as unsigned, if a caller
	# needs to, is the caller's business, the same way this project leaves
	# an `[Network("u32")]` on a C# `ulong` to the C# compiler.
	func write_i64(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 8)
		buf.encode_s64(start, value)

	func write_u64(value: int) -> void:
		var start := buf.size()
		buf.resize(start + 8)
		buf.encode_u64(start, value)

	# Raw IEEE 754 bits, 4 bytes Little Endian - not normalized: NaN
	# payloads survive and -0.0 stays distinct from 0.0.
	func write_f32(value: float) -> void:
		var start := buf.size()
		buf.resize(start + 4)
		buf.encode_float(start, value)

	func write_f64(value: float) -> void:
		var start := buf.size()
		buf.resize(start + 8)
		buf.encode_double(start, value)

	# A uint32 UTF-8 byte length, then those bytes. The length counts
	# bytes, not characters.
	func write_string(value: String) -> void:
		var utf8 := value.to_utf8_buffer()
		write_u32(utf8.size())
		buf.append_array(utf8)

	# A uint32 length, then the raw bytes.
	func write_bytes(value: PackedByteArray) -> void:
		write_u32(value.size())
		buf.append_array(value)

	# Writes an Array<T>'s element count (RFC-0002 §6) - the caller writes
	# each element itself, in order, right after.
	func write_array_count(count: int) -> void:
		write_u32(count)

# Reader reads Cyclone-encoded values from a borrowed buffer.
#
# Malformed input is always a DecodeError, returned - never thrown, GDScript
# has no exceptions - and a failed read leaves the cursor where it was.
#
# Every read below returns a 2-element Array, `[value, error]`, with
# `error` null on success - the nearest GDScript has to Go's `(value,
# err)`, since GDScript cannot destructure a multi-value return.
class Reader:
	var buf: PackedByteArray
	var pos: int = 0
	var limits: Limits

	func _init(bytes: PackedByteArray, with_limits: Limits = null) -> void:
		buf = bytes
		pos = 0
		limits = with_limits if with_limits != null else Limits.new()

	func position() -> int:
		return pos

	func remaining() -> int:
		return buf.size() - pos

	func is_empty() -> bool:
		return remaining() == 0

	func read_bool() -> Array:
		var result := read_u8()
		if result[1] != null:
			return [false, result[1]]
		var value: int = result[0]
		if value == 0:
			return [false, null]
		if value == 1:
			return [true, null]
		pos -= 1
		var error := DecodeError.new()
		error.kind = "invalid_bool"
		error.invalid_byte = value
		return [false, error]

	func read_i8() -> Array:
		var taken := _take(1)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_s8(0), null]

	func read_u8() -> Array:
		var taken := _take(1)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_u8(0), null]

	func read_i16() -> Array:
		var taken := _take(2)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_s16(0), null]

	func read_u16() -> Array:
		var taken := _take(2)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_u16(0), null]

	func read_i32() -> Array:
		var taken := _take(4)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_s32(0), null]

	func read_u32() -> Array:
		var taken := _take(4)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_u32(0), null]

	func read_i64() -> Array:
		var taken := _take(8)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_s64(0), null]

	func read_u64() -> Array:
		var taken := _take(8)
		if taken[1] != null:
			return [0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_u64(0), null]

	func read_f32() -> Array:
		var taken := _take(4)
		if taken[1] != null:
			return [0.0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_float(0), null]

	func read_f64() -> Array:
		var taken := _take(8)
		if taken[1] != null:
			return [0.0, taken[1]]
		var bytes: PackedByteArray = taken[0]
		return [bytes.decode_double(0), null]

	# A uint32 UTF-8 byte length, then that many bytes. The length is
	# checked against the limit and against the bytes actually remaining
	# before anything is allocated.
	func read_string() -> Array:
		var start := pos
		var length_result := _read_length(limits.max_string_len)
		if length_result[1] != null:
			return ["", length_result[1]]
		var length: int = length_result[0]

		var taken := _take_checked(length, start)
		if taken[1] != null:
			return ["", taken[1]]
		var bytes: PackedByteArray = taken[0]

		var text := bytes.get_string_from_utf8()
		if text == "" and length != 0:
			pos = start
			var error := DecodeError.new()
			error.kind = "invalid_utf8"
			return ["", error]
		return [text, null]

	# A uint32 length, then that many raw bytes.
	func read_bytes() -> Array:
		var start := pos
		var length_result := _read_length(limits.max_bytes_len)
		if length_result[1] != null:
			return [PackedByteArray(), length_result[1]]
		var length: int = length_result[0]
		return _take_checked(length, start)

	# Reads an Array<T>'s element count (RFC-0002 §6), checked against
	# limits.max_array_count before the caller reads a single element -
	# the same allocation guard read_string/read_bytes apply to their own
	# length prefix. Returns [count, error], the same two-slot convention
	# every read here follows.
	func read_array_count() -> Array:
		return _read_length(limits.max_array_count)

	func _read_length(limit: int) -> Array:
		var start := pos
		var result := read_u32()
		if result[1] != null:
			return [0, result[1]]
		var length: int = result[0]
		if length > limit:
			pos = start
			var error := DecodeError.new()
			error.kind = "length_overflow"
			error.length = length
			error.limit = limit
			return [0, error]
		return [length, null]

	func _take_checked(length: int, start: int) -> Array:
		var left := remaining()
		if length > left:
			pos = start
			var error := DecodeError.new()
			error.kind = "unexpected_eof"
			error.needed = length
			error.remaining = left
			return [PackedByteArray(), error]
		return _take(length)

	# Borrows the next `length` bytes and advances the cursor - the single
	# place the remaining-bytes check lives, so no read path can slice past
	# the end.
	func _take(length: int) -> Array:
		var left := remaining()
		if length > left:
			var error := DecodeError.new()
			error.kind = "unexpected_eof"
			error.needed = length
			error.remaining = left
			return [PackedByteArray(), error]
		var out := buf.slice(pos, pos + length)
		pos += length
		return [out, null]

# ======================================================================
# Codecs - one per codec each model declared, in declaration order.
# ======================================================================

# DeviceStateEdgeCodec is the "edge" codec for DeviceState, generated from its Cyclone attributes.
class DeviceStateEdgeCodec:
	# Writes the "edge" fields of value, in declaration order.
	func encode(writer: Writer, value: DeviceState) -> void:
		writer.write_u32(value.id)
		writer.write_f32(value.temperature)

	# Reads the "edge" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: DeviceState) -> DecodeError:
		var id_result := reader.read_u32()
		if id_result[1] != null:
			return id_result[1]
		value.id = id_result[0]
		var temperature_result := reader.read_f32()
		if temperature_result[1] != null:
			return temperature_result[1]
		value.temperature = temperature_result[0]
		return null

# DeviceStateUnityCodec is the "unity" codec for DeviceState, generated from its Cyclone attributes.
class DeviceStateUnityCodec:
	# Writes the "unity" fields of value, in declaration order.
	func encode(writer: Writer, value: DeviceState) -> void:
		writer.write_u32(value.id)
		writer.write_string(value.display_name)

	# Reads the "unity" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: DeviceState) -> DecodeError:
		var id_result := reader.read_u32()
		if id_result[1] != null:
			return id_result[1]
		value.id = id_result[0]
		var display_name_result := reader.read_string()
		if display_name_result[1] != null:
			return display_name_result[1]
		value.display_name = display_name_result[0]
		return null

# EveryPrimitiveAllCodec is the "all" codec for EveryPrimitive, generated from its Cyclone attributes.
class EveryPrimitiveAllCodec:
	# Writes the "all" fields of value, in declaration order.
	func encode(writer: Writer, value: EveryPrimitive) -> void:
		writer.write_bool(value.flag)
		writer.write_i8(value.a)
		writer.write_u8(value.b)
		writer.write_i16(value.c)
		writer.write_u16(value.d)
		writer.write_i32(value.e)
		writer.write_u32(value.f)
		writer.write_i64(value.g)
		writer.write_u64(value.h)
		writer.write_f32(value.i)
		writer.write_f64(value.j)
		writer.write_string(value.k)
		writer.write_bytes(value.l)

	# Reads the "all" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: EveryPrimitive) -> DecodeError:
		var flag_result := reader.read_bool()
		if flag_result[1] != null:
			return flag_result[1]
		value.flag = flag_result[0]
		var a_result := reader.read_i8()
		if a_result[1] != null:
			return a_result[1]
		value.a = a_result[0]
		var b_result := reader.read_u8()
		if b_result[1] != null:
			return b_result[1]
		value.b = b_result[0]
		var c_result := reader.read_i16()
		if c_result[1] != null:
			return c_result[1]
		value.c = c_result[0]
		var d_result := reader.read_u16()
		if d_result[1] != null:
			return d_result[1]
		value.d = d_result[0]
		var e_result := reader.read_i32()
		if e_result[1] != null:
			return e_result[1]
		value.e = e_result[0]
		var f_result := reader.read_u32()
		if f_result[1] != null:
			return f_result[1]
		value.f = f_result[0]
		var g_result := reader.read_i64()
		if g_result[1] != null:
			return g_result[1]
		value.g = g_result[0]
		var h_result := reader.read_u64()
		if h_result[1] != null:
			return h_result[1]
		value.h = h_result[0]
		var i_result := reader.read_f32()
		if i_result[1] != null:
			return i_result[1]
		value.i = i_result[0]
		var j_result := reader.read_f64()
		if j_result[1] != null:
			return j_result[1]
		value.j = j_result[0]
		var k_result := reader.read_string()
		if k_result[1] != null:
			return k_result[1]
		value.k = k_result[0]
		var l_result := reader.read_bytes()
		if l_result[1] != null:
			return l_result[1]
		value.l = l_result[0]
		return null

# NoFieldsJoinedLonelyCodec is the "lonely" codec for NoFieldsJoined, generated from its Cyclone attributes.
class NoFieldsJoinedLonelyCodec:
	# Writes the "lonely" fields of value, in declaration order.
	func encode(writer: Writer, value: NoFieldsJoined) -> void:
		pass

	# Reads the "lonely" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: NoFieldsJoined) -> DecodeError:
		return null

# PlayerEdgeCodec is the "edge" codec for Player, generated from its Cyclone attributes.
class PlayerEdgeCodec:
	# Writes the "edge" fields of value, in declaration order.
	func encode(writer: Writer, value: Player) -> void:
		writer.write_u32(value.hp)
		writer.write_f32(value.speed)
		PlayerInfoEdgeCodec.new().encode(writer, value.info)

	# Reads the "edge" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Player) -> DecodeError:
		var hp_result := reader.read_u32()
		if hp_result[1] != null:
			return hp_result[1]
		value.hp = hp_result[0]
		var speed_result := reader.read_f32()
		if speed_result[1] != null:
			return speed_result[1]
		value.speed = speed_result[0]
		var info_error = PlayerInfoEdgeCodec.new().decode(reader, value.info)
		if info_error != null:
			return info_error
		return null

# PlayerInfoEdgeCodec is the "edge" codec for PlayerInfo, generated from its Cyclone attributes.
class PlayerInfoEdgeCodec:
	# Writes the "edge" fields of value, in declaration order.
	func encode(writer: Writer, value: PlayerInfo) -> void:
		writer.write_u32(value.level)

	# Reads the "edge" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: PlayerInfo) -> DecodeError:
		var level_result := reader.read_u32()
		if level_result[1] != null:
			return level_result[1]
		value.level = level_result[0]
		return null

# TeamEdgeCodec is the "edge" codec for Team, generated from its Cyclone attributes.
class TeamEdgeCodec:
	# Writes the "edge" fields of value, in declaration order.
	func encode(writer: Writer, value: Team) -> void:
		writer.write_array_count(value.scores.size())
		for element in value.scores:
			writer.write_u32(element)
		writer.write_array_count(value.names.size())
		for element in value.names:
			writer.write_string(element)
		writer.write_array_count(value.players.size())
		for element in value.players:
			PlayerInfoEdgeCodec.new().encode(writer, element)

	# Reads the "edge" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Team) -> DecodeError:
		var scores_count_result := reader.read_array_count()
		if scores_count_result[1] != null:
			return scores_count_result[1]
		var scores_elements := []
		for i in range(scores_count_result[0]):
			var element_result = reader.read_u32()
			if element_result[1] != null:
				return element_result[1]
			scores_elements.append(element_result[0])
		value.scores = scores_elements
		var names_count_result := reader.read_array_count()
		if names_count_result[1] != null:
			return names_count_result[1]
		var names_elements := []
		for i in range(names_count_result[0]):
			var element_result = reader.read_string()
			if element_result[1] != null:
				return element_result[1]
			names_elements.append(element_result[0])
		value.names = names_elements
		var players_count_result := reader.read_array_count()
		if players_count_result[1] != null:
			return players_count_result[1]
		var players_elements := []
		for i in range(players_count_result[0]):
			var element = PlayerInfo.new()
			var element_error = PlayerInfoEdgeCodec.new().decode(reader, element)
			if element_error != null:
				return element_error
			players_elements.append(element)
		value.players = players_elements
		return null

# TelemetryEdgeCodec is the "edge" codec for Telemetry, generated from its Cyclone attributes.
class TelemetryEdgeCodec:
	# Writes the "edge" fields of value, in declaration order.
	func encode(writer: Writer, value: Telemetry) -> void:
		writer.write_u64(value.sequence)

	# Reads the "edge" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Telemetry) -> DecodeError:
		var sequence_result := reader.read_u64()
		if sequence_result[1] != null:
			return sequence_result[1]
		value.sequence = sequence_result[0]
		return null

# TelemetryOrangePiCodec is the "orange_pi" codec for Telemetry, generated from its Cyclone attributes.
class TelemetryOrangePiCodec:
	# Writes the "orange_pi" fields of value, in declaration order.
	func encode(writer: Writer, value: Telemetry) -> void:
		writer.write_u64(value.sequence)

	# Reads the "orange_pi" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Telemetry) -> DecodeError:
		var sequence_result := reader.read_u64()
		if sequence_result[1] != null:
			return sequence_result[1]
		value.sequence = sequence_result[0]
		return null

# TelemetryUnityCodec is the "unity" codec for Telemetry, generated from its Cyclone attributes.
class TelemetryUnityCodec:
	# Writes the "unity" fields of value, in declaration order.
	func encode(writer: Writer, value: Telemetry) -> void:
		writer.write_u64(value.sequence)

	# Reads the "unity" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Telemetry) -> DecodeError:
		var sequence_result := reader.read_u64()
		if sequence_result[1] != null:
			return sequence_result[1]
		value.sequence = sequence_result[0]
		return null

# TelemetryCustomACodec is the "custom_a" codec for Telemetry, generated from its Cyclone attributes.
class TelemetryCustomACodec:
	# Writes the "custom_a" fields of value, in declaration order.
	func encode(writer: Writer, value: Telemetry) -> void:
		writer.write_u64(value.sequence)

	# Reads the "custom_a" fields into value, in declaration order.
	# Fields this codec does not carry are left as they were, which is what lets one
	# model be split across several codecs.
	func decode(reader: Reader, value: Telemetry) -> DecodeError:
		var sequence_result := reader.read_u64()
		if sequence_result[1] != null:
			return sequence_result[1]
		value.sequence = sequence_result[0]
		return null
