// Generated by cyclonec. Do not edit.
//
// Sources:
//     device_state.cs
//
// This file is self-contained. It carries the Cyclone runtime — Writer,
// Reader, DecodeException, Limits — as well as every codec, so there is
// nothing to add to your .csproj and nothing to import. Add it to your
// project (cyclone.codec.cs) and it compiles.
//
// A nested model field must already hold an instance before Decode fills
// its routed fields — a property initializer (`= new();`) is enough.
#nullable disable

// ==========================================================================
// Cyclone runtime — RFC-0002, carried verbatim.
//
// Not generated from your models: this block is identical in every file
// cyclonec writes. It is here so the file is self-contained.
// ==========================================================================

/// A byte stream that does not satisfy the Cyclone Specification.
public sealed class DecodeException : System.Exception
{
    private DecodeException(string message) : base(message) { }

    /// Fewer bytes remain than the value being read requires.
    public static DecodeException UnexpectedEof(long needed, long remaining) =>
        new DecodeException(
            $"unexpected eof: needed {needed} bytes, {remaining} remaining");

    /// A `bool` byte that is neither `0x00` nor `0x01` (RFC-0002 §3).
    public static DecodeException InvalidBool(byte value) =>
        new DecodeException($"invalid bool: 0x{value:X2} is neither 0x00 nor 0x01");

    /// A `string` region that is not valid UTF-8.
    public static DecodeException InvalidUtf8() =>
        new DecodeException("invalid utf-8 in string");

    /// A length field beyond the configured limit.
    public static DecodeException LengthOverflow(long length, long limit) =>
        new DecodeException($"length overflow: length {length} exceeds limit {limit}");
}

/// Allocation guards applied while decoding (RFC-0002 §4).
///
/// A `u32` length can claim up to 4 GiB, so a decoder that allocates straight
/// from an untrusted one is a denial-of-service target. These are **not part of
/// the wire format**: two peers with different limits may disagree about a byte
/// stream, and neither is wrong.
public struct Limits
{
    /// Largest accepted UTF-8 byte length of a `string`.
    public long MaxStringLength;

    /// Largest accepted byte length of a `bytes` blob.
    public long MaxBytesLength;

    /// The permissive default: `uint.MaxValue` for every field.
    public static Limits Unlimited => new Limits
    {
        MaxStringLength = uint.MaxValue,
        MaxBytesLength = uint.MaxValue,
    };
}

/// Appends Cyclone-encoded values to a growable buffer.
///
/// Every multi-byte value is Little Endian, with no padding, no alignment and
/// no metadata between values.
public sealed class Writer
{
    private readonly System.Collections.Generic.List<byte> _buffer =
        new System.Collections.Generic.List<byte>();

    /// The bytes written so far.
    public byte[] ToArray() => _buffer.ToArray();

    /// The number of bytes written so far.
    public int Length => _buffer.Count;

    /// Writes a `bool` as one byte: `0x00` or `0x01`, never anything else.
    public void WriteBool(bool value) => _buffer.Add(value ? (byte)0x01 : (byte)0x00);

    /// Writes an `i8` as 1 byte.
    public void WriteInt8(sbyte value) => _buffer.Add(unchecked((byte)value));

    /// Writes a `u8` as 1 byte.
    public void WriteUInt8(byte value) => _buffer.Add(value);

    /// Writes an `i16` as 2 bytes, Little Endian.
    public void WriteInt16(short value) => WriteLittleEndian(unchecked((ushort)value), 2);

    /// Writes a `u16` as 2 bytes, Little Endian.
    public void WriteUInt16(ushort value) => WriteLittleEndian(value, 2);

    /// Writes an `i32` as 4 bytes, Little Endian.
    public void WriteInt32(int value) => WriteLittleEndian(unchecked((uint)value), 4);

    /// Writes a `u32` as 4 bytes, Little Endian.
    public void WriteUInt32(uint value) => WriteLittleEndian(value, 4);

    /// Writes an `i64` as 8 bytes, Little Endian.
    public void WriteInt64(long value) => WriteLittleEndian(unchecked((ulong)value), 8);

    /// Writes a `u64` as 8 bytes, Little Endian.
    public void WriteUInt64(ulong value) => WriteLittleEndian(value, 8);

    /// Writes an `f32` as its raw IEEE 754 bits, 4 bytes Little Endian.
    ///
    /// The bit pattern is written unmodified: `NaN` payloads survive and `-0.0`
    /// stays distinct from `0.0`.
    public void WriteFloat32(float value) =>
        WriteLittleEndian(System.BitConverter.SingleToUInt32Bits(value), 4);

    /// Writes an `f64` as its raw IEEE 754 bits, 8 bytes Little Endian.
    public void WriteFloat64(double value) =>
        WriteLittleEndian(System.BitConverter.DoubleToUInt64Bits(value), 8);

    /// Writes a `string` as a `u32` UTF-8 **byte** length, then those bytes.
    ///
    /// The length counts bytes, not characters.
    public void WriteString(string value)
    {
        byte[] bytes = System.Text.Encoding.UTF8.GetBytes(value);
        WriteUInt32((uint)bytes.Length);
        _buffer.AddRange(bytes);
    }

    /// Writes a `bytes` blob as a `u32` length, then the raw bytes.
    public void WriteBytes(byte[] value)
    {
        WriteUInt32((uint)value.Length);
        _buffer.AddRange(value);
    }

    private void WriteLittleEndian(ulong value, int byteCount)
    {
        for (int i = 0; i < byteCount; i++)
        {
            _buffer.Add((byte)(value >> (8 * i)));
        }
    }
}

/// Reads Cyclone-encoded values from a borrowed buffer.
///
/// Malformed input is always a <see cref="DecodeException"/>, never a silent
/// wrong answer, and a failed read leaves the cursor where it was.
public ref struct Reader
{
    private readonly System.ReadOnlySpan<byte> _buffer;
    private int _position;
    private readonly Limits _limits;

    /// Creates a reader over `buffer` with <see cref="Limits.Unlimited"/>.
    public Reader(System.ReadOnlySpan<byte> buffer) : this(buffer, Limits.Unlimited) { }

    /// Creates a reader over `buffer` with explicit allocation guards.
    public Reader(System.ReadOnlySpan<byte> buffer, Limits limits)
    {
        _buffer = buffer;
        _position = 0;
        _limits = limits;
    }

    /// The cursor position, in bytes from the start.
    public int Position => _position;

    /// The number of bytes left to read.
    public int Remaining => _buffer.Length - _position;

    /// Whether the cursor has reached the end.
    public bool IsEmpty => Remaining == 0;

    /// Reads a `bool` from 1 byte.
    public bool ReadBool()
    {
        byte value = ReadUInt8();
        if (value == 0x00) return false;
        if (value == 0x01) return true;
        _position -= 1;
        throw DecodeException.InvalidBool(value);
    }

    /// Reads an `i8` from 1 byte.
    public sbyte ReadInt8() => unchecked((sbyte)Take(1)[0]);

    /// Reads a `u8` from 1 byte.
    public byte ReadUInt8() => Take(1)[0];

    /// Reads an `i16` from 2 bytes, Little Endian.
    public short ReadInt16() => unchecked((short)ReadLittleEndian(2));

    /// Reads a `u16` from 2 bytes, Little Endian.
    public ushort ReadUInt16() => (ushort)ReadLittleEndian(2);

    /// Reads an `i32` from 4 bytes, Little Endian.
    public int ReadInt32() => unchecked((int)ReadLittleEndian(4));

    /// Reads a `u32` from 4 bytes, Little Endian.
    public uint ReadUInt32() => (uint)ReadLittleEndian(4);

    /// Reads an `i64` from 8 bytes, Little Endian.
    public long ReadInt64() => unchecked((long)ReadLittleEndian(8));

    /// Reads a `u64` from 8 bytes, Little Endian.
    public ulong ReadUInt64() => ReadLittleEndian(8);

    /// Reads an `f32` from its raw 4-byte IEEE 754 bits.
    ///
    /// The bits are reinterpreted, never normalized.
    public float ReadFloat32() => System.BitConverter.UInt32BitsToSingle(ReadUInt32());

    /// Reads an `f64` from its raw 8-byte IEEE 754 bits.
    public double ReadFloat64() => System.BitConverter.UInt64BitsToDouble(ReadUInt64());

    /// Reads a `string`: a `u32` UTF-8 byte length, then that many bytes.
    ///
    /// The length is checked against the limit and against the bytes actually
    /// remaining **before** anything is allocated.
    public string ReadString()
    {
        int start = _position;
        int len = ReadLength(_limits.MaxStringLength);
        System.ReadOnlySpan<byte> bytes = TakeChecked(len, start);

        try
        {
            return new System.Text.UTF8Encoding(false, true).GetString(bytes);
        }
        catch (System.Text.DecoderFallbackException)
        {
            _position = start;
            throw DecodeException.InvalidUtf8();
        }
    }

    /// Reads a `bytes` blob: a `u32` length, then that many raw bytes.
    public byte[] ReadBytes()
    {
        int start = _position;
        int len = ReadLength(_limits.MaxBytesLength);
        return TakeChecked(len, start).ToArray();
    }

    private int ReadLength(long limit)
    {
        int start = _position;
        uint len = ReadUInt32();
        if (len > limit)
        {
            _position = start;
            throw DecodeException.LengthOverflow(len, limit);
        }
        return (int)len;
    }

    private System.ReadOnlySpan<byte> TakeChecked(int len, int start)
    {
        int remaining = Remaining;
        if (len > remaining)
        {
            _position = start;
            throw DecodeException.UnexpectedEof(len, remaining);
        }
        return Take(len);
    }

    private ulong ReadLittleEndian(int byteCount)
    {
        System.ReadOnlySpan<byte> bytes = Take(byteCount);
        ulong value = 0;
        for (int i = 0; i < byteCount; i++)
        {
            value |= (ulong)bytes[i] << (8 * i);
        }
        return value;
    }

    /// Borrows the next `len` bytes and advances the cursor.
    ///
    /// The single place the remaining-bytes check lives, so no read path can
    /// allocate or index past the end.
    private System.ReadOnlySpan<byte> Take(int len)
    {
        int remaining = Remaining;
        if (len > remaining)
        {
            throw DecodeException.UnexpectedEof(len, remaining);
        }
        System.ReadOnlySpan<byte> bytes = _buffer.Slice(_position, len);
        _position += len;
        return bytes;
    }
}

// ==========================================================================
// Codecs — one per codec each model declared, in declaration order.
// ==========================================================================

/// <summary>The <c>edge</c> codec for <see cref="DeviceState"/>, generated from its Cyclone attributes.</summary>
public static class DeviceStateEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, DeviceState value)
    {
        writer.WriteUInt32(value.Id);
        writer.WriteFloat32(value.Temperature);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref DeviceState value)
    {
        value.Id = reader.ReadUInt32();
        value.Temperature = reader.ReadFloat32();
    }
}

/// <summary>The <c>unity</c> codec for <see cref="DeviceState"/>, generated from its Cyclone attributes.</summary>
public static class DeviceStateUnityCodec
{
    /// <summary>Writes the <c>unity</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, DeviceState value)
    {
        writer.WriteUInt32(value.Id);
        writer.WriteString(value.DisplayName);
    }

    /// <summary>Reads the <c>unity</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref DeviceState value)
    {
        value.Id = reader.ReadUInt32();
        value.DisplayName = reader.ReadString();
    }
}

/// <summary>The <c>edge</c> codec for <see cref="Telemetry"/>, generated from its Cyclone attributes.</summary>
public static class TelemetryEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Telemetry value)
    {
        writer.WriteUInt64(value.Sequence);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Telemetry value)
    {
        value.Sequence = reader.ReadUInt64();
    }
}

/// <summary>The <c>orange_pi</c> codec for <see cref="Telemetry"/>, generated from its Cyclone attributes.</summary>
public static class TelemetryOrangePiCodec
{
    /// <summary>Writes the <c>orange_pi</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Telemetry value)
    {
        writer.WriteUInt64(value.Sequence);
    }

    /// <summary>Reads the <c>orange_pi</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Telemetry value)
    {
        value.Sequence = reader.ReadUInt64();
    }
}

/// <summary>The <c>unity</c> codec for <see cref="Telemetry"/>, generated from its Cyclone attributes.</summary>
public static class TelemetryUnityCodec
{
    /// <summary>Writes the <c>unity</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Telemetry value)
    {
        writer.WriteUInt64(value.Sequence);
    }

    /// <summary>Reads the <c>unity</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Telemetry value)
    {
        value.Sequence = reader.ReadUInt64();
    }
}

/// <summary>The <c>custom_a</c> codec for <see cref="Telemetry"/>, generated from its Cyclone attributes.</summary>
public static class TelemetryCustomACodec
{
    /// <summary>Writes the <c>custom_a</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Telemetry value)
    {
        writer.WriteUInt64(value.Sequence);
    }

    /// <summary>Reads the <c>custom_a</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Telemetry value)
    {
        value.Sequence = reader.ReadUInt64();
    }
}

/// <summary>The <c>edge</c> codec for <see cref="PlayerInfo"/>, generated from its Cyclone attributes.</summary>
public static class PlayerInfoEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, PlayerInfo value)
    {
        writer.WriteUInt32(value.Level);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref PlayerInfo value)
    {
        value.Level = reader.ReadUInt32();
    }
}

/// <summary>The <c>edge</c> codec for <see cref="Player"/>, generated from its Cyclone attributes.</summary>
public static class PlayerEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Player value)
    {
        writer.WriteUInt32(value.Hp);
        writer.WriteFloat32(value.Speed);
        PlayerInfoEdgeCodec.Encode(writer, value.Info);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Player value)
    {
        value.Hp = reader.ReadUInt32();
        value.Speed = reader.ReadFloat32();
        var infoValue = value.Info;
        PlayerInfoEdgeCodec.Decode(ref reader, ref infoValue);
        value.Info = infoValue;
    }
}

/// <summary>The <c>all</c> codec for <see cref="EveryPrimitive"/>, generated from its Cyclone attributes.</summary>
public static class EveryPrimitiveAllCodec
{
    /// <summary>Writes the <c>all</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, EveryPrimitive value)
    {
        writer.WriteBool(value.Flag);
        writer.WriteInt8(value.A);
        writer.WriteUInt8(value.B);
        writer.WriteInt16(value.C);
        writer.WriteUInt16(value.D);
        writer.WriteInt32(value.E);
        writer.WriteUInt32(value.F);
        writer.WriteInt64(value.G);
        writer.WriteUInt64(value.H);
        writer.WriteFloat32(value.I);
        writer.WriteFloat64(value.J);
        writer.WriteString(value.K);
        writer.WriteBytes(value.L);
    }

    /// <summary>Reads the <c>all</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref EveryPrimitive value)
    {
        value.Flag = reader.ReadBool();
        value.A = reader.ReadInt8();
        value.B = reader.ReadUInt8();
        value.C = reader.ReadInt16();
        value.D = reader.ReadUInt16();
        value.E = reader.ReadInt32();
        value.F = reader.ReadUInt32();
        value.G = reader.ReadInt64();
        value.H = reader.ReadUInt64();
        value.I = reader.ReadFloat32();
        value.J = reader.ReadFloat64();
        value.K = reader.ReadString();
        value.L = reader.ReadBytes();
    }
}

/// <summary>The <c>lonely</c> codec for <see cref="NoFieldsJoined"/>, generated from its Cyclone attributes.</summary>
public static class NoFieldsJoinedLonelyCodec
{
    /// <summary>Writes the <c>lonely</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, NoFieldsJoined value)
    {
    }

    /// <summary>Reads the <c>lonely</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref NoFieldsJoined value)
    {
    }
}

/// <summary>The <c>edge</c> codec for <see cref="AfterTheUnmarkedClass"/>, generated from its Cyclone attributes.</summary>
public static class AfterTheUnmarkedClassEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, AfterTheUnmarkedClass value)
    {
        writer.WriteUInt32(value.Value);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref AfterTheUnmarkedClass value)
    {
        value.Value = reader.ReadUInt32();
    }
}

/// <summary>The <c>edge</c> codec for <see cref="Point"/>, generated from its Cyclone attributes.</summary>
public static class PointEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, Point value)
    {
        writer.WriteInt32(value.X);
        writer.WriteInt32(value.Y);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref Point value)
    {
        value.X = reader.ReadInt32();
        value.Y = reader.ReadInt32();
    }
}

/// <summary>The <c>edge</c> codec for <see cref="WithFields"/>, generated from its Cyclone attributes.</summary>
public static class WithFieldsEdgeCodec
{
    /// <summary>Writes the <c>edge</c> fields of <paramref name="value"/>, in declaration order.</summary>
    public static void Encode(Writer writer, WithFields value)
    {
        writer.WriteUInt32(value.Id);
        writer.WriteString(value.Name);
    }

    /// <summary>Reads the <c>edge</c> fields into <paramref name="value"/>, in declaration order.</summary>
    /// <remarks>Fields this codec does not carry are left as they were, which is
    /// what lets one model be split across several codecs.</remarks>
    public static void Decode(ref Reader reader, ref WithFields value)
    {
        value.Id = reader.ReadUInt32();
        value.Name = reader.ReadString();
    }
}
