package fixtures

// Generated by cyclonec. Do not edit.
//
// Sources:
//     device_state.go
//
// This file is self-contained: it carries the Cyclone runtime (Writer,
// Reader, DecodeError, Limits) as well as every codec, so there is nothing
// else to add to go.mod. It belongs in the same package as your
// models (cyclone.codec.go).

// ==========================================================================
// Cyclone runtime - RFC-0002, carried verbatim.
//
// Not generated from your models: this block is identical in every file
// cyclonec writes. It is here so the file is self-contained.
// ==========================================================================

import (
	"encoding/binary"
	"fmt"
	"math"
	"unicode/utf8"
)

// DecodeError is a byte stream that does not satisfy the Cyclone
// Specification.
type DecodeError struct {
	// Kind names which Specification error condition this is.
	Kind string
	// Needed is the number of bytes a read needed. Set for "unexpected_eof".
	Needed int
	// Remaining is the number of bytes actually left. Set for "unexpected_eof".
	Remaining int
	// InvalidByte is the offending byte. Set for "invalid_bool".
	InvalidByte byte
	// Length is the length or count read from the stream. Set for
	// "length_overflow".
	Length int
	// Limit is the configured limit it exceeded. Set for "length_overflow".
	Limit int
}

func (e *DecodeError) Error() string {
	switch e.Kind {
	case "unexpected_eof":
		return fmt.Sprintf("unexpected eof: needed %d bytes, %d remaining", e.Needed, e.Remaining)
	case "invalid_bool":
		return fmt.Sprintf("invalid bool: 0x%02X is neither 0x00 nor 0x01", e.InvalidByte)
	case "invalid_utf8":
		return "invalid utf-8 in string"
	case "length_overflow":
		return fmt.Sprintf("length overflow: length %d exceeds limit %d", e.Length, e.Limit)
	default:
		return "cyclone: decode error"
	}
}

func errUnexpectedEOF(needed, remaining int) error {
	return &DecodeError{Kind: "unexpected_eof", Needed: needed, Remaining: remaining}
}

func errInvalidBool(value byte) error {
	return &DecodeError{Kind: "invalid_bool", InvalidByte: value}
}

func errInvalidUTF8() error {
	return &DecodeError{Kind: "invalid_utf8"}
}

func errLengthOverflow(length, limit int) error {
	return &DecodeError{Kind: "length_overflow", Length: length, Limit: limit}
}

// Limits are allocation guards applied while decoding (RFC-0002 §4).
//
// A uint32 length can claim up to 4 GiB, so a decoder that allocates straight
// from an untrusted one is a denial-of-service target. These are not part of
// the wire format: two peers with different limits may disagree about a byte
// stream, and neither is wrong.
type Limits struct {
	// MaxStringLen is the largest accepted UTF-8 byte length of a string.
	MaxStringLen int
	// MaxBytesLen is the largest accepted byte length of a bytes blob.
	MaxBytesLen int
	// MaxArrayCount is the largest accepted element count of an Array<T>
	// (RFC-0002 §6). A uint32 count can claim up to 4 GiB of elements
	// before a single one is even read, so this guards allocation the
	// same way MaxStringLen/MaxBytesLen do.
	MaxArrayCount int
}

// UnlimitedLimits is the permissive default: math.MaxUint32 for every field.
var UnlimitedLimits = Limits{
	MaxStringLen:  math.MaxUint32,
	MaxBytesLen:   math.MaxUint32,
	MaxArrayCount: math.MaxUint32,
}

// Writer appends Cyclone-encoded values to a growable buffer.
//
// Every multi-byte value is Little Endian, with no padding, no alignment and
// no metadata between values.
type Writer struct {
	buf []byte
}

// NewWriter creates an empty writer.
func NewWriter() *Writer {
	return &Writer{}
}

// Bytes returns the bytes written so far.
func (w *Writer) Bytes() []byte {
	if w.buf == nil {
		return []byte{}
	}
	return w.buf
}

// Len returns the number of bytes written so far.
func (w *Writer) Len() int {
	return len(w.buf)
}

// WriteBool writes a bool as one byte: 0x00 or 0x01, never anything else.
func (w *Writer) WriteBool(value bool) {
	if value {
		w.buf = append(w.buf, 0x01)
	} else {
		w.buf = append(w.buf, 0x00)
	}
}

// WriteI8 writes an int8 as 1 byte.
func (w *Writer) WriteI8(value int8) {
	w.buf = append(w.buf, byte(value))
}

// WriteU8 writes a uint8 as 1 byte.
func (w *Writer) WriteU8(value uint8) {
	w.buf = append(w.buf, value)
}

// WriteI16 writes an int16 as 2 bytes, Little Endian.
func (w *Writer) WriteI16(value int16) {
	w.WriteU16(uint16(value))
}

// WriteU16 writes a uint16 as 2 bytes, Little Endian.
func (w *Writer) WriteU16(value uint16) {
	var tmp [2]byte
	binary.LittleEndian.PutUint16(tmp[:], value)
	w.buf = append(w.buf, tmp[:]...)
}

// WriteI32 writes an int32 as 4 bytes, Little Endian.
func (w *Writer) WriteI32(value int32) {
	w.WriteU32(uint32(value))
}

// WriteU32 writes a uint32 as 4 bytes, Little Endian.
func (w *Writer) WriteU32(value uint32) {
	var tmp [4]byte
	binary.LittleEndian.PutUint32(tmp[:], value)
	w.buf = append(w.buf, tmp[:]...)
}

// WriteI64 writes an int64 as 8 bytes, Little Endian.
func (w *Writer) WriteI64(value int64) {
	w.WriteU64(uint64(value))
}

// WriteU64 writes a uint64 as 8 bytes, Little Endian.
func (w *Writer) WriteU64(value uint64) {
	var tmp [8]byte
	binary.LittleEndian.PutUint64(tmp[:], value)
	w.buf = append(w.buf, tmp[:]...)
}

// WriteF32 writes a float32 as its raw IEEE 754 bits, 4 bytes Little Endian.
//
// The bit pattern is written unmodified: NaN payloads survive and -0.0 stays
// distinct from 0.0.
func (w *Writer) WriteF32(value float32) {
	w.WriteU32(math.Float32bits(value))
}

// WriteF64 writes a float64 as its raw IEEE 754 bits, 8 bytes Little Endian.
func (w *Writer) WriteF64(value float64) {
	w.WriteU64(math.Float64bits(value))
}

// WriteString writes a string as a uint32 UTF-8 byte length, then those bytes.
//
// The length counts bytes, not characters.
func (w *Writer) WriteString(value string) {
	w.WriteU32(uint32(len(value)))
	w.buf = append(w.buf, value...)
}

// WriteBytes writes a bytes blob as a uint32 length, then the raw bytes.
func (w *Writer) WriteBytes(value []byte) {
	w.WriteU32(uint32(len(value)))
	w.buf = append(w.buf, value...)
}

// WriteArrayCount writes an Array<T>'s element count (RFC-0002 §6) - the
// caller writes each element itself, in order, right after.
func (w *Writer) WriteArrayCount(count int) {
	w.WriteU32(uint32(count))
}

// Reader reads Cyclone-encoded values from a borrowed buffer.
//
// Malformed input is always a *DecodeError, never a panic, and a failed read
// leaves the cursor where it was.
type Reader struct {
	buf    []byte
	pos    int
	limits Limits
}

// NewReader creates a reader over buf with the permissive UnlimitedLimits.
func NewReader(buf []byte) *Reader {
	return &Reader{buf: buf, limits: UnlimitedLimits}
}

// NewReaderWithLimits creates a reader over buf with explicit allocation
// guards.
func NewReaderWithLimits(buf []byte, limits Limits) *Reader {
	return &Reader{buf: buf, limits: limits}
}

// Position returns the cursor position, in bytes from the start.
func (r *Reader) Position() int {
	return r.pos
}

// Remaining returns the number of bytes left to read.
func (r *Reader) Remaining() int {
	return len(r.buf) - r.pos
}

// IsEmpty reports whether the cursor has reached the end.
func (r *Reader) IsEmpty() bool {
	return r.Remaining() == 0
}

// ReadBool reads a bool from 1 byte.
//
// Returns InvalidBool for any byte but 0x00 and 0x01 - "non-zero means true"
// is not permitted.
func (r *Reader) ReadBool() (bool, error) {
	value, err := r.ReadU8()
	if err != nil {
		return false, err
	}
	switch value {
	case 0x00:
		return false, nil
	case 0x01:
		return true, nil
	default:
		r.pos--
		return false, errInvalidBool(value)
	}
}

// ReadI8 reads an int8 from 1 byte.
func (r *Reader) ReadI8() (int8, error) {
	value, err := r.ReadU8()
	return int8(value), err
}

// ReadU8 reads a uint8 from 1 byte.
func (r *Reader) ReadU8() (uint8, error) {
	bytes, err := r.take(1)
	if err != nil {
		return 0, err
	}
	return bytes[0], nil
}

// ReadI16 reads an int16 from 2 bytes, Little Endian.
func (r *Reader) ReadI16() (int16, error) {
	value, err := r.ReadU16()
	return int16(value), err
}

// ReadU16 reads a uint16 from 2 bytes, Little Endian.
func (r *Reader) ReadU16() (uint16, error) {
	bytes, err := r.take(2)
	if err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint16(bytes), nil
}

// ReadI32 reads an int32 from 4 bytes, Little Endian.
func (r *Reader) ReadI32() (int32, error) {
	value, err := r.ReadU32()
	return int32(value), err
}

// ReadU32 reads a uint32 from 4 bytes, Little Endian.
func (r *Reader) ReadU32() (uint32, error) {
	bytes, err := r.take(4)
	if err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint32(bytes), nil
}

// ReadI64 reads an int64 from 8 bytes, Little Endian.
func (r *Reader) ReadI64() (int64, error) {
	value, err := r.ReadU64()
	return int64(value), err
}

// ReadU64 reads a uint64 from 8 bytes, Little Endian.
func (r *Reader) ReadU64() (uint64, error) {
	bytes, err := r.take(8)
	if err != nil {
		return 0, err
	}
	return binary.LittleEndian.Uint64(bytes), nil
}

// ReadF32 reads a float32 from its raw 4-byte IEEE 754 bits.
//
// The bits are reinterpreted, never normalized.
func (r *Reader) ReadF32() (float32, error) {
	bits, err := r.ReadU32()
	if err != nil {
		return 0, err
	}
	return math.Float32frombits(bits), nil
}

// ReadF64 reads a float64 from its raw 8-byte IEEE 754 bits.
func (r *Reader) ReadF64() (float64, error) {
	bits, err := r.ReadU64()
	if err != nil {
		return 0, err
	}
	return math.Float64frombits(bits), nil
}

// ReadString reads a string: a uint32 UTF-8 byte length, then that many
// bytes.
//
// The length is checked against the limit and against the bytes actually
// remaining before anything is allocated.
func (r *Reader) ReadString() (string, error) {
	start := r.pos
	length, err := r.readLength(r.limits.MaxStringLen)
	if err != nil {
		return "", err
	}

	bytes, err := r.takeChecked(length, start)
	if err != nil {
		return "", err
	}

	if !utf8.Valid(bytes) {
		r.pos = start
		return "", errInvalidUTF8()
	}
	return string(bytes), nil
}

// ReadBytes reads a bytes blob: a uint32 length, then that many raw bytes.
func (r *Reader) ReadBytes() ([]byte, error) {
	start := r.pos
	length, err := r.readLength(r.limits.MaxBytesLen)
	if err != nil {
		return nil, err
	}

	bytes, err := r.takeChecked(length, start)
	if err != nil {
		return nil, err
	}
	out := make([]byte, len(bytes))
	copy(out, bytes)
	return out, nil
}

// ReadArrayCount reads an Array<T>'s element count (RFC-0002 §6), checked
// against Limits.MaxArrayCount before the caller reads a single element -
// the same allocation guard ReadString and ReadBytes apply to their own
// length prefix.
func (r *Reader) ReadArrayCount() (int, error) {
	return r.readLength(r.limits.MaxArrayCount)
}

func (r *Reader) readLength(limit int) (int, error) {
	start := r.pos
	length, err := r.ReadU32()
	if err != nil {
		return 0, err
	}
	if int(length) > limit {
		r.pos = start
		return 0, errLengthOverflow(int(length), limit)
	}
	return int(length), nil
}

func (r *Reader) takeChecked(length, start int) ([]byte, error) {
	remaining := r.Remaining()
	if length > remaining {
		r.pos = start
		return nil, errUnexpectedEOF(length, remaining)
	}
	return r.take(length)
}

// take borrows the next length bytes and advances the cursor.
//
// The single place the remaining-bytes check lives, so no read path can
// allocate or index past the end.
func (r *Reader) take(length int) ([]byte, error) {
	remaining := r.Remaining()
	if length > remaining {
		return nil, errUnexpectedEOF(length, remaining)
	}
	bytes := r.buf[r.pos : r.pos+length]
	r.pos += length
	return bytes, nil
}

// ==========================================================================
// Codecs - one per codec each model declared, in declaration order.
// ==========================================================================

// DeviceStateEdgeCodec is the "edge" codec for DeviceState, generated from its Cyclone attributes.
type DeviceStateEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (DeviceStateEdgeCodec) Encode(w *Writer, value *DeviceState) {
	w.WriteU32(value.ID)
	w.WriteF32(value.Temperature)
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (DeviceStateEdgeCodec) Decode(r *Reader, value *DeviceState) error {
	var err error

	value.ID, err = r.ReadU32()
	if err != nil {
		return err
	}

	value.Temperature, err = r.ReadF32()
	if err != nil {
		return err
	}

	return nil
}

// DeviceStateUnityCodec is the "unity" codec for DeviceState, generated from its Cyclone attributes.
type DeviceStateUnityCodec struct{}

// Encode writes the "unity" fields of value, in declaration order.
func (DeviceStateUnityCodec) Encode(w *Writer, value *DeviceState) {
	w.WriteU32(value.ID)
	w.WriteString(value.Name)
}

// Decode reads the "unity" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (DeviceStateUnityCodec) Decode(r *Reader, value *DeviceState) error {
	var err error

	value.ID, err = r.ReadU32()
	if err != nil {
		return err
	}

	value.Name, err = r.ReadString()
	if err != nil {
		return err
	}

	return nil
}

// TelemetryEdgeCodec is the "edge" codec for Telemetry, generated from its Cyclone attributes.
type TelemetryEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (TelemetryEdgeCodec) Encode(w *Writer, value *Telemetry) {
	w.WriteU64(value.Sequence)
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (TelemetryEdgeCodec) Decode(r *Reader, value *Telemetry) error {
	var err error

	value.Sequence, err = r.ReadU64()
	if err != nil {
		return err
	}

	return nil
}

// TelemetryOrangePiCodec is the "orange_pi" codec for Telemetry, generated from its Cyclone attributes.
type TelemetryOrangePiCodec struct{}

// Encode writes the "orange_pi" fields of value, in declaration order.
func (TelemetryOrangePiCodec) Encode(w *Writer, value *Telemetry) {
	w.WriteU64(value.Sequence)
}

// Decode reads the "orange_pi" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (TelemetryOrangePiCodec) Decode(r *Reader, value *Telemetry) error {
	var err error

	value.Sequence, err = r.ReadU64()
	if err != nil {
		return err
	}

	return nil
}

// TelemetryUnityCodec is the "unity" codec for Telemetry, generated from its Cyclone attributes.
type TelemetryUnityCodec struct{}

// Encode writes the "unity" fields of value, in declaration order.
func (TelemetryUnityCodec) Encode(w *Writer, value *Telemetry) {
	w.WriteU64(value.Sequence)
}

// Decode reads the "unity" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (TelemetryUnityCodec) Decode(r *Reader, value *Telemetry) error {
	var err error

	value.Sequence, err = r.ReadU64()
	if err != nil {
		return err
	}

	return nil
}

// TelemetryCustomACodec is the "custom_a" codec for Telemetry, generated from its Cyclone attributes.
type TelemetryCustomACodec struct{}

// Encode writes the "custom_a" fields of value, in declaration order.
func (TelemetryCustomACodec) Encode(w *Writer, value *Telemetry) {
	w.WriteU64(value.Sequence)
}

// Decode reads the "custom_a" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (TelemetryCustomACodec) Decode(r *Reader, value *Telemetry) error {
	var err error

	value.Sequence, err = r.ReadU64()
	if err != nil {
		return err
	}

	return nil
}

// PlayerInfoEdgeCodec is the "edge" codec for PlayerInfo, generated from its Cyclone attributes.
type PlayerInfoEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (PlayerInfoEdgeCodec) Encode(w *Writer, value *PlayerInfo) {
	w.WriteU32(value.Level)
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (PlayerInfoEdgeCodec) Decode(r *Reader, value *PlayerInfo) error {
	var err error

	value.Level, err = r.ReadU32()
	if err != nil {
		return err
	}

	return nil
}

// PlayerEdgeCodec is the "edge" codec for Player, generated from its Cyclone attributes.
type PlayerEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (PlayerEdgeCodec) Encode(w *Writer, value *Player) {
	w.WriteU32(value.HP)
	w.WriteF32(value.Speed)
	(PlayerInfoEdgeCodec{}).Encode(w, &value.Info)
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (PlayerEdgeCodec) Decode(r *Reader, value *Player) error {
	var err error

	value.HP, err = r.ReadU32()
	if err != nil {
		return err
	}

	value.Speed, err = r.ReadF32()
	if err != nil {
		return err
	}

	err = (PlayerInfoEdgeCodec{}).Decode(r, &value.Info)
	if err != nil {
		return err
	}

	return nil
}

// TeamEdgeCodec is the "edge" codec for Team, generated from its Cyclone attributes.
type TeamEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (TeamEdgeCodec) Encode(w *Writer, value *Team) {
	w.WriteArrayCount(len(value.Scores))
	for _, element := range value.Scores {
		w.WriteU32(element)
	}
	w.WriteArrayCount(len(value.Names))
	for _, element := range value.Names {
		w.WriteString(element)
	}
	w.WriteArrayCount(len(value.Players))
	for _, element := range value.Players {
		(PlayerInfoEdgeCodec{}).Encode(w, &element)
	}
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (TeamEdgeCodec) Decode(r *Reader, value *Team) error {
	var err error

	scoresCount, err := r.ReadArrayCount()
	if err != nil {
		return err
	}
	scoresElements := make([]uint32, 0, scoresCount)
	for i := 0; i < scoresCount; i++ {
		var element uint32
		element, err = r.ReadU32()
		if err != nil {
			return err
		}
		scoresElements = append(scoresElements, element)
	}
	value.Scores = scoresElements

	namesCount, err := r.ReadArrayCount()
	if err != nil {
		return err
	}
	namesElements := make([]string, 0, namesCount)
	for i := 0; i < namesCount; i++ {
		var element string
		element, err = r.ReadString()
		if err != nil {
			return err
		}
		namesElements = append(namesElements, element)
	}
	value.Names = namesElements

	playersCount, err := r.ReadArrayCount()
	if err != nil {
		return err
	}
	playersElements := make([]PlayerInfo, 0, playersCount)
	for i := 0; i < playersCount; i++ {
		var element PlayerInfo
		err = (PlayerInfoEdgeCodec{}).Decode(r, &element)
		if err != nil {
			return err
		}
		playersElements = append(playersElements, element)
	}
	value.Players = playersElements

	return nil
}

// EveryPrimitiveAllCodec is the "all" codec for EveryPrimitive, generated from its Cyclone attributes.
type EveryPrimitiveAllCodec struct{}

// Encode writes the "all" fields of value, in declaration order.
func (EveryPrimitiveAllCodec) Encode(w *Writer, value *EveryPrimitive) {
	w.WriteBool(value.Flag)
	w.WriteI8(value.A)
	w.WriteU8(value.B)
	w.WriteI16(value.C)
	w.WriteU16(value.D)
	w.WriteI32(value.E)
	w.WriteU32(value.F)
	w.WriteI64(value.G)
	w.WriteU64(value.H)
	w.WriteF32(value.I)
	w.WriteF64(value.J)
	w.WriteString(value.K)
	w.WriteBytes(value.L)
}

// Decode reads the "all" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (EveryPrimitiveAllCodec) Decode(r *Reader, value *EveryPrimitive) error {
	var err error

	value.Flag, err = r.ReadBool()
	if err != nil {
		return err
	}

	value.A, err = r.ReadI8()
	if err != nil {
		return err
	}

	value.B, err = r.ReadU8()
	if err != nil {
		return err
	}

	value.C, err = r.ReadI16()
	if err != nil {
		return err
	}

	value.D, err = r.ReadU16()
	if err != nil {
		return err
	}

	value.E, err = r.ReadI32()
	if err != nil {
		return err
	}

	value.F, err = r.ReadU32()
	if err != nil {
		return err
	}

	value.G, err = r.ReadI64()
	if err != nil {
		return err
	}

	value.H, err = r.ReadU64()
	if err != nil {
		return err
	}

	value.I, err = r.ReadF32()
	if err != nil {
		return err
	}

	value.J, err = r.ReadF64()
	if err != nil {
		return err
	}

	value.K, err = r.ReadString()
	if err != nil {
		return err
	}

	value.L, err = r.ReadBytes()
	if err != nil {
		return err
	}

	return nil
}

// NoFieldsJoinedLonelyCodec is the "lonely" codec for NoFieldsJoined, generated from its Cyclone attributes.
type NoFieldsJoinedLonelyCodec struct{}

// Encode writes the "lonely" fields of value, in declaration order.
func (NoFieldsJoinedLonelyCodec) Encode(w *Writer, value *NoFieldsJoined) {
}

// Decode reads the "lonely" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (NoFieldsJoinedLonelyCodec) Decode(r *Reader, value *NoFieldsJoined) error {
	return nil
}

// AfterTheUnmarkedStructEdgeCodec is the "edge" codec for AfterTheUnmarkedStruct, generated from its Cyclone attributes.
type AfterTheUnmarkedStructEdgeCodec struct{}

// Encode writes the "edge" fields of value, in declaration order.
func (AfterTheUnmarkedStructEdgeCodec) Encode(w *Writer, value *AfterTheUnmarkedStruct) {
	w.WriteU32(value.Value)
}

// Decode reads the "edge" fields into value, in declaration order.
//
// Fields this codec does not carry are left as they were, which is what lets one
// model be split across several codecs.
func (AfterTheUnmarkedStructEdgeCodec) Decode(r *Reader, value *AfterTheUnmarkedStruct) error {
	var err error

	value.Value, err = r.ReadU32()
	if err != nil {
		return err
	}

	return nil
}
