//! [`Model`]s → C# source.
//!
//! The C# counterpart of [`super::rust`]. Same rule, same shape: a model is
//! walked once, a codec at a time, a field at a time, and each field appends
//! one statement. The network type is looked up in [`PRIMITIVES`], and anything
//! not in that table is another model's name, spelled into a call - `cyclonec`
//! never checks that the call resolves; the C# compiler does.
//!
//! # Kept equivalent to the Rust backend
//!
//! Both backends read the identical [`Model`] / [`Field`] shape (see
//! [`crate::model`]), produce the same codec name for the same schema
//! (`DeviceState` + `edge` → `DeviceStateEdgeCodec` on both sides), route fields
//! to codecs by the same rule, and call a runtime method that performs the same
//! RFC-0002 byte layout - [`super::csharp_runtime`] is written against the same
//! specification as [`super::rust_runtime`], method for method. What differs is
//! syntax only: C# spells the field access `value.Id`, not `value.id`, because
//! that is what the source wrote; it does not spell a different wire format.
//!
//! # One difference `ref` forces
//!
//! Rust decode takes `&mut value.field` straight into a nested call, because a
//! struct field is never absent. A C# property cannot be passed by `ref` at
//! all, so a nested model field is decoded through a local: read the existing
//! value out, decode into it by `ref`, assign it back. See [`decode_field`].
//! This preserves the same "leaves fields this codec does not carry alone"
//! guarantee the Rust side has - including recursively, into the nested model -
//! provided the field already holds an instance, the same requirement Rust's
//! version has (there, the language enforces it; here, the caller must).

use crate::model::{pascal_case, Field, Model};

/// The runtime method each network type maps to.
///
/// Every name in this table comes from RFC-0002's Reader / Writer interface,
/// spelled the way [`super::csharp_runtime`] spells it. A name that is not in
/// it is not looked up, resolved, or imported - it is another model, and the
/// call is spelled and left for the C# compiler to resolve or reject.
const PRIMITIVES: &[(&str, &str, &str)] = &[
    // (network type, writer method, reader method)
    ("bool", "WriteBool", "ReadBool"),
    ("i8", "WriteInt8", "ReadInt8"),
    ("u8", "WriteUInt8", "ReadUInt8"),
    ("i16", "WriteInt16", "ReadInt16"),
    ("u16", "WriteUInt16", "ReadUInt16"),
    ("i32", "WriteInt32", "ReadInt32"),
    ("u32", "WriteUInt32", "ReadUInt32"),
    ("i64", "WriteInt64", "ReadInt64"),
    ("u64", "WriteUInt64", "ReadUInt64"),
    ("f32", "WriteFloat32", "ReadFloat32"),
    ("f64", "WriteFloat64", "ReadFloat64"),
    ("string", "WriteString", "ReadString"),
    ("bytes", "WriteBytes", "ReadBytes"),
];

/// The name of the generated file when the output path names a directory.
pub const DEFAULT_FILE_NAME: &str = "cyclone.codec.cs";

/// The suffix a C# output path is recognised by.
pub const EXTENSION: &str = "cs";

/// Renders one self-contained file: the runtime, then every codec every C#
/// model declared.
///
/// See [`super::rust::render`] - same contract, same determinism guarantee.
/// `file_name` appears only in the header comment; C# has no `include!`, so a
/// generated file is simply added to the project (or picked up by the SDK's
/// default `**/*.cs` glob) rather than referenced by name.
pub fn render(sources: &[String], models: &[Model], file_name: &str) -> Option<String> {
    if models.iter().all(|model| model.codecs.is_empty()) {
        return None;
    }

    let mut out = String::with_capacity(16 * 1024);

    out.push_str("// Generated by cyclonec. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Sources:\n");
    for source in sources {
        out.push_str(&format!("//     {source}\n"));
    }
    out.push_str("//\n");
    out.push_str("// This file is self-contained. It carries the Cyclone runtime - Writer,\n");
    out.push_str("// Reader, DecodeException, Limits - as well as every codec, so there is\n");
    out.push_str("// nothing to add to your .csproj and nothing to import. Add it to your\n");
    out.push_str(&format!("// project ({file_name}) and it compiles.\n"));
    out.push_str("//\n");
    out.push_str("// A nested model field must already hold an instance before Decode fills\n");
    out.push_str("// its routed fields - a property initializer (`= new();`) is enough.\n");
    out.push_str("#nullable disable\n");

    out.push_str(super::csharp_runtime::RUNTIME);

    out.push_str("\n// ==========================================================================\n");
    out.push_str("// Codecs - one per codec each model declared, in declaration order.\n");
    out.push_str("// ==========================================================================\n");

    for model in models {
        for codec in &model.codecs {
            out.push('\n');
            codec_type(&mut out, model, codec);
        }
    }

    Some(out)
}

/// Writes one codec: the class, and its `Encode` / `Decode`.
fn codec_type(out: &mut String, model: &Model, codec: &str) {
    let name = codec_name(&model.name, codec);
    let model_name = &model.name;

    out.push_str(&format!(
        "/// <summary>The <c>{codec}</c> codec for <see cref=\"{model_name}\"/>, generated from its Cyclone attributes.</summary>\n"
    ));
    out.push_str(&format!("public static class {name}\n{{\n"));

    // -------------------------------------------------------------- encode
    out.push_str(&format!(
        "    /// <summary>Writes the <c>{codec}</c> fields of <paramref name=\"value\"/>, in declaration order.</summary>\n"
    ));
    out.push_str(&format!(
        "    public static void Encode(Writer writer, {model_name} value)\n    {{\n"
    ));
    for field in model.fields_in(codec) {
        out.push_str("        ");
        encode_field(out, field, codec);
        out.push('\n');
    }
    out.push_str("    }\n\n");

    // -------------------------------------------------------------- decode
    out.push_str(&format!(
        "    /// <summary>Reads the <c>{codec}</c> fields into <paramref name=\"value\"/>, in declaration order.</summary>\n"
    ));
    out.push_str(
        "    /// <remarks>Fields this codec does not carry are left as they were, which is\n",
    );
    out.push_str("    /// what lets one model be split across several codecs.</remarks>\n");
    out.push_str(&format!(
        "    public static void Decode(ref Reader reader, ref {model_name} value)\n    {{\n"
    ));
    for field in model.fields_in(codec) {
        out.push_str("        ");
        decode_field(out, field, codec);
    }
    out.push_str("    }\n");

    out.push_str("}\n");
}

/// Emits one encode statement.
///
/// Unlike Rust, nothing here is written by reference: `string` and `byte[]` are
/// already reference types in C#, so `writer.WriteString(value.Name)` needs no
/// `&` - there is no C# equivalent of that borrow to spell.
fn encode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    match primitive(&field.network_type) {
        Some((writer_method, _)) => {
            out.push_str(&format!("writer.{writer_method}(value.{name});"));
        }
        // A model. The codec carries over, so a nested model is written by the
        // same profile the outer one is being written by.
        None => {
            let nested = codec_name(&field.network_type, codec);
            out.push_str(&format!("{nested}.Encode(writer, value.{name});"));
        }
    }
}

/// Emits the statement(s) that decode one field, ending in a newline.
///
/// A primitive is one assignment. A nested model needs the `ref`-through-a-local
/// dance the module header explains: a C# property is not an addressable
/// storage location, so it cannot be passed `ref` directly.
fn decode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    match primitive(&field.network_type) {
        Some((_, reader_method)) => {
            out.push_str(&format!("value.{name} = reader.{reader_method}();\n"));
        }
        None => {
            let nested = codec_name(&field.network_type, codec);
            let local = local_name(name);
            out.push_str(&format!("var {local} = value.{name};\n"));
            out.push_str(&format!("        {nested}.Decode(ref reader, ref {local});\n"));
            out.push_str(&format!("        value.{name} = {local};\n"));
        }
    }
}

/// The generated type name: `DeviceState` + `edge` → `DeviceStateEdgeCodec`.
fn codec_name(model: &str, codec: &str) -> String {
    format!("{model}{}Codec", pascal_case(codec))
}

/// Looks a network type up in [`PRIMITIVES`].
fn primitive(network_type: &str) -> Option<(&'static str, &'static str)> {
    PRIMITIVES
        .iter()
        .find(|(name, ..)| *name == network_type)
        .map(|(_, writer, reader)| (*writer, *reader))
}

/// A local variable name that cannot collide with `writer`, `reader`, `value`,
/// or another field's temporary in the same method.
fn local_name(field_name: &str) -> String {
    let mut chars = field_name.chars();
    let mut local = match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>(),
        None => String::new(),
    };
    local.push_str(chars.as_str());
    local.push_str("Value");
    local
}
