//! [`Model`]s → Go source.
//!
//! The Go counterpart of [`super::rust`] and [`super::csharp`]. Same rule, same
//! shape: a model is walked once, a codec at a time, a field at a time, and
//! each field appends one statement. The network type is looked up in
//! [`PRIMITIVES`], and anything not in that table is another model's name,
//! spelled into a call - `cyclonec` never checks that the call resolves; the Go
//! compiler does.
//!
//! # Kept equivalent to the other two backends
//!
//! All three backends read the identical [`Model`] / [`Field`] shape, produce
//! the same codec name for the same schema, route fields to codecs by the same
//! rule, and call a runtime method that performs the same RFC-0002 byte layout
//! - [`super::go_runtime`] is written against the same specification as
//! [`super::rust_runtime`] and [`super::csharp_runtime`], method for method.
//!
//! # What Go forces that the others do not
//!
//! Go has no exceptions, so `Decode` returns `error` and every read is
//! followed by an explicit check - the shape h.md §10 itself specifies. And Go
//! compiles by *package*, not by file: a generated file has to declare the same
//! `package` its models live in, or nothing in it will resolve. See
//! [`render`]'s `package_name` parameter.

use crate::model::{pascal_case, Field, Model};

/// The runtime method each network type maps to.
///
/// Every name in this table comes from RFC-0002's Reader / Writer interface,
/// spelled the way [`super::go_runtime`] spells it - and the way h.md §10's own
/// example spells it (`WriteU32`/`ReadU32`, not `WriteUInt32`). A name that is
/// not in it is not looked up, resolved, or imported - it is another model, and
/// the call is spelled and left for the Go compiler to resolve or reject.
const PRIMITIVES: &[(&str, &str, &str)] = &[
    // (network type, writer method, reader method)
    ("bool", "WriteBool", "ReadBool"),
    ("i8", "WriteI8", "ReadI8"),
    ("u8", "WriteU8", "ReadU8"),
    ("i16", "WriteI16", "ReadI16"),
    ("u16", "WriteU16", "ReadU16"),
    ("i32", "WriteI32", "ReadI32"),
    ("u32", "WriteU32", "ReadU32"),
    ("i64", "WriteI64", "ReadI64"),
    ("u64", "WriteU64", "ReadU64"),
    ("f32", "WriteF32", "ReadF32"),
    ("f64", "WriteF64", "ReadF64"),
    ("string", "WriteString", "ReadString"),
    ("bytes", "WriteBytes", "ReadBytes"),
];

/// The name of the generated file when the output path names a directory.
pub const DEFAULT_FILE_NAME: &str = "cyclone.codec.go";

/// The suffix a Go output path is recognised by.
pub const EXTENSION: &str = "go";

/// The package clause used when no source declared one.
///
/// Every Go file needs a `package` line to compile at all; this is reached
/// only if `cyclonec` is asked to generate from Go models that (unusually)
/// never named their own package.
const FALLBACK_PACKAGE: &str = "cyclone";

/// Renders one self-contained file: the package clause, the runtime, then
/// every codec every Go model declared.
///
/// See [`super::rust::render`] - same contract, same determinism guarantee.
/// `package_name` is the `package` clause every source file in this run
/// declared (Go compiles by directory, and every file in one directory must
/// share one package name, so the generator trusts the first one it saw rather
/// than re-deriving it); `None` falls back to [`FALLBACK_PACKAGE`].
pub fn render(
    sources: &[String],
    models: &[Model],
    file_name: &str,
    package_name: Option<&str>,
) -> Option<String> {
    if models.iter().all(|model| model.codecs.is_empty()) {
        return None;
    }

    let mut out = String::with_capacity(16 * 1024);

    out.push_str(&format!("package {}\n", package_name.unwrap_or(FALLBACK_PACKAGE)));
    out.push_str("\n// Generated by cyclonec. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Sources:\n");
    for source in sources {
        out.push_str(&format!("//     {source}\n"));
    }
    out.push_str("//\n");
    out.push_str("// This file is self-contained: it carries the Cyclone runtime (Writer,\n");
    out.push_str("// Reader, DecodeError, Limits) as well as every codec, so there is nothing\n");
    out.push_str(&format!("// else to add to go.mod. It belongs in the same package as your\n// models ({file_name}).\n"));

    out.push_str(super::go_runtime::RUNTIME);

    out.push_str("\n// ==========================================================================\n");
    out.push_str("// Codecs - one per codec each model declared, in declaration order.\n");
    out.push_str("// ==========================================================================\n");

    for model in models {
        for codec in &model.codecs {
            out.push('\n');
            codec_type(&mut out, model, codec);
        }
    }

    Some(out)
}

/// Writes one codec: the type, and its `Encode` / `Decode` methods.
fn codec_type(out: &mut String, model: &Model, codec: &str) {
    let name = codec_name(&model.name, codec);
    let model_name = &model.name;

    out.push_str(&format!(
        "// {name} is the {codec:?} codec for {model_name}, generated from its Cyclone attributes.\n"
    ));
    out.push_str(&format!("type {name} struct{{}}\n\n"));

    // -------------------------------------------------------------- encode
    out.push_str(&format!(
        "// Encode writes the {codec:?} fields of value, in declaration order.\n"
    ));
    out.push_str(&format!("func ({name}) Encode(w *Writer, value *{model_name}) {{\n"));
    for field in model.fields_in(codec) {
        out.push('\t');
        encode_field(out, field, codec);
        out.push('\n');
    }
    out.push_str("}\n\n");

    // -------------------------------------------------------------- decode
    out.push_str(&format!(
        "// Decode reads the {codec:?} fields into value, in declaration order.\n"
    ));
    out.push_str("//\n");
    out.push_str(
        "// Fields this codec does not carry are left as they were, which is what lets one\n",
    );
    out.push_str("// model be split across several codecs.\n");
    out.push_str(&format!(
        "func ({name}) Decode(r *Reader, value *{model_name}) error {{\n"
    ));

    let fields: Vec<&Field> = model.fields_in(codec).collect();
    if fields.is_empty() {
        out.push_str("\treturn nil\n");
    } else {
        out.push_str("\tvar err error\n\n");
        for (index, field) in fields.iter().enumerate() {
            decode_field(out, field, codec);
            if index + 1 < fields.len() {
                out.push('\n');
            }
        }
        out.push_str("\n\treturn nil\n");
    }
    out.push_str("}\n");
}

/// Emits one encode statement.
fn encode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    match primitive(&field.network_type) {
        Some((writer_method, _)) => {
            out.push_str(&format!("w.{writer_method}(value.{name})"));
        }
        // A model. The codec carries over, so a nested model is written by the
        // same profile the outer one is being written by.
        None => {
            let nested = codec_name(&field.network_type, codec);
            out.push_str(&format!("({nested}{{}}).Encode(w, &value.{name})"));
        }
    }
}

/// Emits the statements that decode one field.
///
/// A primitive is one assignment through the shared `err` local, checked
/// immediately after - the shape h.md §10 itself specifies. A nested model
/// takes the field's address directly: unlike a C# property, a Go struct field
/// reached through a pointer is addressable, so no local-variable workaround is
/// needed here.
fn decode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    match primitive(&field.network_type) {
        Some((_, reader_method)) => {
            out.push_str(&format!("\tvalue.{name}, err = r.{reader_method}()\n"));
        }
        None => {
            let nested = codec_name(&field.network_type, codec);
            out.push_str(&format!("\terr = ({nested}{{}}).Decode(r, &value.{name})\n"));
        }
    }
    out.push_str("\tif err != nil {\n\t\treturn err\n\t}\n");
}

/// The generated type name: `DeviceState` + `edge` → `DeviceStateEdgeCodec`.
fn codec_name(model: &str, codec: &str) -> String {
    format!("{model}{}Codec", pascal_case(codec))
}

/// Looks a network type up in [`PRIMITIVES`].
fn primitive(network_type: &str) -> Option<(&'static str, &'static str)> {
    PRIMITIVES
        .iter()
        .find(|(name, ..)| *name == network_type)
        .map(|(_, writer, reader)| (*writer, *reader))
}
