//! IR → source, one file per thing.
//!
//! ```text
//! Message  →  Field  →  statement
//! ```
//!
//! Rust, Go, C#, GDScript, C++ and C are generated today - each its own
//! module plus its own runtime constant ([`rust`]/[`rust_runtime`],
//! [`go`]/[`go_runtime`], [`csharp`]/[`csharp_runtime`],
//! [`gdscript`]/[`gdscript_runtime`], [`cpp`]/[`cpp_runtime`],
//! [`c`]/[`c_runtime`]) - and nothing above [`crate::ir`] moves for a
//! seventh.
//!
//! # What a run writes
//!
//! ```text
//! generated/
//!     mod.rs             the module root: declares and re-exports the rest
//!     runtime.rs         the RFC-0002 runtime, verbatim
//!     handshake.rs       fingerprints and message ids
//!     player_edge.rs     one codec
//!     player_unity.rs    another
//! ```
//!
//! One file per model per codec, never one file for the whole project: a codec
//! is the unit that changes, and a diff should show which one did.
//!
//! # It is a module tree, not something to `include!`
//!
//! `cyclonec_old` wrote one file and had the user paste it into their own
//! module, which is why nothing in it needed an import - the models were
//! already in scope at the paste site. A *tree* cannot work that way. Each file
//! here is an ordinary Rust module: it is named like one (`player_edge.rs`, not
//! `player.edge.rs` - a dot is not part of an identifier, so `mod` could never
//! reach it), it `use`s every type it names, including the model it encodes,
//! and the whole tree is mounted the ordinary way:
//!
//! ```ignore
//! mod generated;
//! use generated::{PlayerEdgeCodec, Reader, Writer};
//! ```
//!
//! Which leaves one thing the generator has to be told rather than assume:
//! *where the models live*. It reads that off the source layout by default -
//! `src/models/player.rs` is `crate::models::player` - and `model_path` in
//! `cyclone.toml` overrides it. See [`crate::generate::model_paths`].
//!
//! The tree is flat. Model names are unique within a schema, so
//! `<model>_<codec>` is unique too, and a flat tree is one every file reaches
//! with a single `super::`.

pub mod c;
pub mod c_handshake;
pub mod c_runtime;
pub mod cpp;
pub mod cpp_handshake;
pub mod cpp_runtime;
pub mod csharp;
pub mod csharp_handshake;
pub mod csharp_runtime;
pub mod gdscript;
pub mod gdscript_handshake;
pub mod gdscript_runtime;
pub mod go;
pub mod go_handshake;
pub mod go_runtime;
pub mod handshake;
pub mod rust;
pub mod rust_runtime;

use crate::ir::WireType;
use crate::model::pascal_case;
use crate::timestamp;

/// The generated codec type name, shared by every backend: `Player` + `edge`
/// → `PlayerEdgeCodec`.
pub fn codec_type_name(model: &str, codec: &str) -> String {
    format!("{model}{}Codec", pascal_case(codec))
}

/// The models whose type name a generated codec writes out literally, for a
/// field of type `ty`.
///
/// Shared by every backend: only an array element is ever constructed by
/// name (`<T as Default>::default()` in Rust's decode loop, `var element T`
/// in Go's) - everything else, including a bare nested-model field, is
/// reached through its codec and never spells the model's own type.
pub fn spelled_types<'a>(ty: &'a WireType, into: &mut std::collections::BTreeSet<&'a str>) {
    if let WireType::Array(element) = ty {
        match element.as_ref() {
            WireType::Model(name) => {
                into.insert(name);
            }
            nested @ WireType::Array(_) => spelled_types(nested, into),
            _ => {}
        }
    }
}

/// The first line of everything this crate writes for Rust, Go and C# - the
/// marker [`crate::generate::is_generated`] and [`crate::generate::obsolete`]
/// look for before treating a file as this generator's own.
pub const MARKER: &str = "// GENERATED BY cyclonec";

/// [`MARKER`]'s GDScript spelling. `//` is integer division in GDScript, not
/// a comment - `#` is GDScript's only line comment syntax, so a `.gd` file
/// this generator writes carries this marker instead. See
/// [`gdscript::Header`].
pub const GDSCRIPT_MARKER: &str = "# GENERATED BY cyclonec";

/// The prefix of the one header line that changes between two otherwise
/// identical Rust, Go or C# runs.
pub const TIMESTAMP_PREFIX: &str = "// generated-at: ";

/// [`TIMESTAMP_PREFIX`]'s GDScript spelling - see [`GDSCRIPT_MARKER`] for why
/// GDScript needs its own.
pub const GDSCRIPT_TIMESTAMP_PREFIX: &str = "# generated-at: ";

/// The [`TIMESTAMP_PREFIX`] variant `line` starts with, if any - checked
/// against both spellings so [`same_but_for_timestamp`] and
/// [`without_timestamp`] work for every backend without having to be told
/// which one produced the text.
fn timestamp_prefix(line: &str) -> Option<&'static str> {
    if line.starts_with(TIMESTAMP_PREFIX) {
        Some(TIMESTAMP_PREFIX)
    } else if line.starts_with(GDSCRIPT_TIMESTAMP_PREFIX) {
        Some(GDSCRIPT_TIMESTAMP_PREFIX)
    } else {
        None
    }
}

/// The root of the generated module tree.
pub const MODULE_ROOT: &str = "mod.rs";

/// The lint attributes every generated file opens with.
///
/// A project uses the codecs it needs and no more, and `mod generated;` is
/// private by default - so every constant and method it does not call is
/// `dead_code` as far as `rustc` is concerned. A warning in a file whose header
/// says DO NOT EDIT is a warning nobody can act on, so the file silences it
/// itself.
pub const FILE_ATTRIBUTES: &str = "#![allow(dead_code, unused_imports)]\n\n";

/// What a generated file's header says about itself.
#[derive(Default)]
pub struct Header<'a> {
    /// The source file the model was read from.
    pub source: Option<&'a str>,
    /// The model, for a codec file.
    pub model: Option<&'a str>,
    /// The codec, for a codec file.
    pub codec: Option<&'a str>,
    /// The fingerprint of whatever this file is about.
    pub fingerprint: Option<String>,
    /// A sentence about what the file is, printed after the machine-readable
    /// lines.
    pub note: Option<&'a str>,
}

impl Header<'_> {
    /// Renders the header, ending in a blank line.
    pub fn render(&self) -> String {
        let mut out = String::with_capacity(512);
        out.push_str(MARKER);
        out.push('\n');
        out.push_str("// DO NOT EDIT MANUALLY\n");
        if let Some(source) = self.source {
            out.push_str(&format!("// source: {source}\n"));
        }
        if let Some(model) = self.model {
            out.push_str(&format!("// model: {model}\n"));
        }
        if let Some(codec) = self.codec {
            out.push_str(&format!("// codec: {codec}\n"));
        }
        if let Some(fingerprint) = &self.fingerprint {
            out.push_str(&format!("// fingerprint: {fingerprint}\n"));
        }
        out.push_str(&format!(
            "// cyclonec-version: {}\n",
            env!("CARGO_PKG_VERSION")
        ));
        out.push_str(TIMESTAMP_PREFIX);
        out.push_str(&timestamp::now_utc());
        out.push('\n');
        if let Some(note) = self.note {
            out.push_str("//\n");
            for line in note.lines() {
                // No trailing space on a blank comment line: a generated file
                // that a linter wants to reformat is a generated file somebody
                // will eventually reformat by hand.
                if line.is_empty() {
                    out.push_str("//\n");
                } else {
                    out.push_str(&format!("// {line}\n"));
                }
            }
        }
        out.push('\n');
        out
    }
}

/// Whether two generated files differ only in their `generated-at:` line.
///
/// The brief asks for a timestamp in every generated header; a timestamp also
/// makes every file differ from itself on every run, which would rewrite the
/// whole tree (and everything watching it would rebuild) each time `cyclonec`
/// ran. Both are satisfiable at once by never letting that one line decide:
/// a file whose only difference is its timestamp is left alone, keeping the
/// timestamp of the run that last actually changed it - which is the date a
/// reader of that header wants anyway.
pub fn same_but_for_timestamp(left: &str, right: &str) -> bool {
    let mut left = left.lines();
    let mut right = right.lines();

    loop {
        match (left.next(), right.next()) {
            (None, None) => return true,
            (Some(one), Some(other)) => {
                if one == other {
                    continue;
                }
                let one_prefix = timestamp_prefix(one);
                if one_prefix.is_some() && one_prefix == timestamp_prefix(other) {
                    continue;
                }
                return false;
            }
            _ => return false,
        }
    }
}

/// A generated file's text with its `generated-at:` line emptied out.
///
/// Anything that hashes a generated file has to hash this and not the file, or
/// the digest changes on every run for a file whose content did not - and then
/// the build graph churns, `--check` fails an hour after a clean generate, and
/// the digest stops meaning "somebody edited this".
pub fn without_timestamp(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for line in text.lines() {
        match timestamp_prefix(line) {
            Some(prefix) => out.push_str(prefix),
            None => out.push_str(line),
        }
        out.push('\n');
    }
    out
}

/// The root of the generated module tree: `mod.rs`.
///
/// `modules` are the generated modules in declaration order; `codecs` are the
/// `(module, type)` pairs re-exported from here, so that a user can name a
/// codec without knowing which file it landed in.
///
/// This is a **module**, not something to `include!`. `cyclonec_old` wrote one
/// file and pasted it into the user's own module, which is why nothing in it
/// needed an import. A tree of files cannot work that way: each file is a
/// module of its own, each imports what it names, and the whole tree is reached
/// the ordinary way -
///
/// ```ignore
/// mod generated;                      // src/generated/mod.rs
/// use generated::{PlayerEdgeCodec, Reader, Writer};
/// ```
pub fn module_root(modules: &[String], codecs: &[(String, String)]) -> String {
    let mut out = Header {
        note: Some(
            "The generated module tree. Mount it the ordinary way - from src/, this\n\
             is `mod generated;` - and everything below is reachable through it:\n\
             \n\
                 mod generated;\n\
                 use generated::{PlayerEdgeCodec, Reader, Writer};\n\
             \n\
             Nothing to add to Cargo.toml and nothing to import from elsewhere: the\n\
             Cyclone runtime is the `runtime` module beside this file.",
        ),
        ..Header::default()
    }
    .render();
    out.push_str(FILE_ATTRIBUTES);

    for module in modules {
        out.push_str(&format!("pub mod {module};\n"));
    }

    out.push_str("\n// Re-exported so that a codec can be named without knowing which file it\n");
    out.push_str("// landed in.\n");
    out.push_str("pub use self::handshake::*;\n");
    out.push_str("pub use self::runtime::{DecodeError, Limits, Reader, Writer};\n");
    for (module, codec) in codecs {
        out.push_str(&format!("pub use self::{module}::{codec};\n"));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::{module_root, same_but_for_timestamp, Header, MARKER};

    #[test]
    fn a_header_carries_what_the_file_is() {
        let header = Header {
            source: Some("src/models/player.rs"),
            model: Some("Player"),
            codec: Some("edge"),
            fingerprint: Some("sha256:abc".to_owned()),
            note: None,
        }
        .render();

        assert!(header.starts_with(MARKER), "{header}");
        assert!(header.contains("// DO NOT EDIT MANUALLY\n"));
        assert!(header.contains("// source: src/models/player.rs\n"));
        assert!(header.contains("// model: Player\n"));
        assert!(header.contains("// codec: edge\n"));
        assert!(header.contains("// fingerprint: sha256:abc\n"));
        assert!(header.contains("// cyclonec-version: "));
        assert!(header.contains("// generated-at: "));
    }

    #[test]
    fn only_the_timestamp_line_is_allowed_to_differ() {
        let one = "// a\n// generated-at: 2026-01-01T00:00:00Z\n// b\n";
        let same = "// a\n// generated-at: 2030-06-06T12:00:00Z\n// b\n";
        let different = "// a\n// generated-at: 2030-06-06T12:00:00Z\n// c\n";

        assert!(same_but_for_timestamp(one, same));
        assert!(!same_but_for_timestamp(one, different));
        assert!(!same_but_for_timestamp(one, "// a\n"));
    }

    #[test]
    fn the_gdscript_timestamp_prefix_is_recognised_too() {
        // `#` is GDScript's own spelling of the same header line - `//`
        // would not compile as a comment there at all.
        let one = "# a\n# generated-at: 2026-01-01T00:00:00Z\n# b\n";
        let same = "# a\n# generated-at: 2030-06-06T12:00:00Z\n# b\n";
        assert!(same_but_for_timestamp(one, same));

        // A `//` file and a `#` file never compare equal on the timestamp
        // line alone, even if by coincidence both happen to be on one -
        // they are two different backends' output.
        let rust_timestamp = "// generated-at: 2026-01-01T00:00:00Z\n";
        let gdscript_timestamp = "# generated-at: 2026-01-01T00:00:00Z\n";
        assert!(!same_but_for_timestamp(rust_timestamp, gdscript_timestamp));
    }

    #[test]
    fn the_root_declares_every_module_and_re_exports_the_codecs() {
        let text = module_root(
            &[
                "runtime".to_owned(),
                "handshake".to_owned(),
                "player_edge".to_owned(),
            ],
            &[("player_edge".to_owned(), "PlayerEdgeCodec".to_owned())],
        );

        assert!(text.contains("pub mod runtime;\n"), "{text}");
        assert!(text.contains("pub mod handshake;\n"), "{text}");
        assert!(text.contains("pub mod player_edge;\n"), "{text}");
        assert!(
            text.contains("pub use self::runtime::{DecodeError, Limits, Reader, Writer};\n"),
            "{text}"
        );
        assert!(
            text.contains("pub use self::player_edge::PlayerEdgeCodec;\n"),
            "{text}"
        );
        // A module tree, not something to paste into somebody else's module.
        assert!(!text.contains("include!"), "{text}");
    }
}
