//! [`Model`]s → Rust source.
//!
//! There is no pass here. A model is walked once, a codec at a time, a field at
//! a time, and each field appends one line. Nothing is analysed on the way: the
//! network type is looked up in a table, and anything not in that table is
//! another model's name, spelled into a call.
//!
//! ```text
//! Model  →  Codec  →  Field  →  statement
//! ```
//!
//! # What it will not write
//!
//! No byte layout, no endianness, no string encoding, no length prefix. Those
//! are the runtime's, already implemented, and re-deriving them here is how two
//! implementations of one wire format start disagreeing. The generator only
//! writes the call.
//!
//! Nor an `encoded_size`, a registry, a `get_codec`, a type id, or anything
//! reached at runtime. A codec is a name known at compile time, and the caller
//! names it directly.
//!
//! # This is one of two backends
//!
//! [`super::csharp`] is the other. Both read the same [`Model`], produce the
//! same codec names for the same schema (see [`crate::model::pascal_case`]),
//! and differ only in the syntax and the runtime method names they write - see
//! that module's header for the shared contract.

use crate::model::{array_element_type, pascal_case, Field, Model};

/// The runtime method each network type maps to, and whether it is written by
/// reference.
///
/// This table is the whole of the generator's type knowledge. Every name in it
/// comes from RFC-0002's Reader / Writer interface; a name that is not in it is
/// not looked up, resolved, or imported - it is another model, and §8 says to
/// spell the call and let `rustc` decide whether it exists.
const PRIMITIVES: &[(&str, &str, &str, bool)] = &[
    // (network type, writer method, reader method, passed by reference)
    ("bool", "write_bool", "read_bool", false),
    ("i8", "write_i8", "read_i8", false),
    ("u8", "write_u8", "read_u8", false),
    ("i16", "write_i16", "read_i16", false),
    ("u16", "write_u16", "read_u16", false),
    ("i32", "write_i32", "read_i32", false),
    ("u32", "write_u32", "read_u32", false),
    ("i64", "write_i64", "read_i64", false),
    ("u64", "write_u64", "read_u64", false),
    ("f32", "write_f32", "read_f32", false),
    ("f64", "write_f64", "read_f64", false),
    ("string", "write_string", "read_string", true),
    ("bytes", "write_bytes", "read_bytes", true),
];

/// The name of the generated file when the output path names a directory.
pub const DEFAULT_FILE_NAME: &str = "cyclone.codec.rs";

/// The suffix a Rust output path is recognised by.
pub const EXTENSION: &str = "rs";

/// Renders one self-contained file: the runtime, then every codec every model
/// declared.
///
/// `sources` is the list of files the models came from, in the order they were
/// read; it appears in the header and nowhere else.
///
/// Returns `None` when there is nothing to write - no models, or none that
/// declared a codec - so no empty file is left behind for the next reader to
/// wonder about.
///
/// The output is deterministic: the same models produce byte-identical text on
/// every machine. The header names the source files and nothing else - no path,
/// no timestamp, no version - which is what makes `--check` mean something.
pub fn render(sources: &[String], models: &[Model], file_name: &str) -> Option<String> {
    if models.iter().all(|model| model.codecs.is_empty()) {
        return None;
    }

    let mut out = String::with_capacity(16 * 1024);

    out.push_str("// Generated by cyclonec. Do not edit.\n");
    out.push_str("//\n");
    out.push_str("// Sources:\n");
    for source in sources {
        out.push_str(&format!("//     {source}\n"));
    }
    out.push_str("//\n");
    out.push_str("// This file is self-contained. It carries the Cyclone runtime - Writer,\n");
    out.push_str("// Reader, DecodeError, Limits - as well as every codec, so there is nothing\n");
    out.push_str("// to add to Cargo.toml and nothing to import. Include it where your models\n");
    out.push_str("// are in scope:\n");
    out.push_str("//\n");
    out.push_str(&format!("//     include!(\"{file_name}\");\n"));

    out.push_str(super::rust_runtime::RUNTIME);

    out.push_str("\n// ==========================================================================\n");
    out.push_str("// Codecs - one per codec each model declared, in declaration order.\n");
    out.push_str("// ==========================================================================\n");

    for model in models {
        for codec in &model.codecs {
            out.push('\n');
            codec_type(&mut out, model, codec);
        }
    }

    Some(out)
}

/// Writes one codec: the type, and its `encode` / `decode`.
fn codec_type(out: &mut String, model: &Model, codec: &str) {
    let name = codec_name(&model.name, codec);
    let model_name = &model.name;

    out.push_str(&format!(
        "/// The `{codec}` codec for [`{model_name}`], generated from its Cyclone attributes.\n"
    ));
    out.push_str(&format!("pub struct {name};\n\n"));
    out.push_str(&format!("impl {name} {{\n"));

    // A codec no field joined is still generated - §15, a declared codec is not
    // the generator's to drop - but its parameters go unread, so they are named
    // to say so rather than warning in every build that compiles the output.
    let unused = if model.fields_in(codec).next().is_none() { "_" } else { "" };

    // -------------------------------------------------------------- encode
    out.push_str(&format!(
        "    /// Writes the `{codec}` fields of `value`, in declaration order.\n"
    ));
    out.push_str(&format!(
        "    pub fn encode({unused}writer: &mut Writer, {unused}value: &{model_name}) {{\n"
    ));
    for field in model.fields_in(codec) {
        out.push_str("        ");
        encode_field(out, field, codec);
        out.push('\n');
    }
    out.push_str("    }\n\n");

    // -------------------------------------------------------------- decode
    out.push_str(&format!(
        "    /// Reads the `{codec}` fields into `value`, in declaration order.\n"
    ));
    out.push_str("    ///\n");
    out.push_str("    /// Fields this codec does not carry are left as they were, which is what\n");
    out.push_str("    /// lets one model be split across several codecs.\n");
    out.push_str(&format!(
        "    pub fn decode({unused}reader: &mut Reader, {unused}value: &mut {model_name}) \
         -> Result<(), DecodeError> {{\n"
    ));
    for field in model.fields_in(codec) {
        out.push_str("        ");
        decode_field(out, field, codec);
        out.push('\n');
    }
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");

    out.push_str("}\n");
}

/// One encode statement - or, for `Array<T>`, a small block: the element
/// count, then a loop writing each one. `T` may be a primitive or another
/// model; either way the array's own codec never comes up, because there is
/// no such thing - only `T`'s.
fn encode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    if let Some(element_type) = array_element_type(&field.network_type) {
        out.push_str(&format!("writer.write_array_count(value.{name}.len());\n"));
        out.push_str(&format!("        for element in value.{name}.iter() {{\n            "));
        encode_value(out, element_type, "element", codec);
        out.push_str("\n        }");
        return;
    }

    match primitive(&field.network_type) {
        Some((writer_method, _, by_reference)) => {
            let borrow = if by_reference { "&" } else { "" };
            out.push_str(&format!("writer.{writer_method}({borrow}value.{name});"));
        }
        // A model. The codec carries over, so a nested model is written by the
        // same profile the outer one is being written by.
        None => {
            let nested = codec_name(&field.network_type, codec);
            out.push_str(&format!("{nested}::encode(writer, &value.{name});"));
        }
    }
}

/// Writes one array element, already bound to `expr` (a `&T`, from the
/// loop's own `element`) - the same primitive-or-nested-model split
/// [`encode_field`] does for a bare field, applied to an element instead of
/// `value.{name}`.
fn encode_value(out: &mut String, element_type: &str, expr: &str, codec: &str) {
    match primitive(element_type) {
        Some((writer_method, _, by_reference)) => {
            // `expr` is already a reference (the loop variable from
            // `.iter()`): a by-reference primitive (`string`/`bytes`) needs
            // no further `&`, and a by-value one needs a deref to get back
            // to the `T` its `write_*` method actually takes.
            if by_reference {
                out.push_str(&format!("writer.{writer_method}({expr});"));
            } else {
                out.push_str(&format!("writer.{writer_method}(*{expr});"));
            }
        }
        None => {
            let nested = codec_name(element_type, codec);
            out.push_str(&format!("{nested}::encode(writer, {expr});"));
        }
    }
}

/// One decode statement - or, for `Array<T>`, a small block: the element
/// count (checked against [`Limits::max_array_count`] before a single
/// element is read), then a loop reading each one into a fresh `Vec`.
fn decode_field(out: &mut String, field: &Field, codec: &str) {
    let name = &field.name;

    if let Some(element_type) = array_element_type(&field.network_type) {
        out.push_str("let array_count = reader.read_array_count()?;\n");
        out.push_str(
            "        let mut elements = ::std::vec::Vec::with_capacity(array_count.min(4096));\n",
        );
        out.push_str("        for _ in 0..array_count {\n");
        out.push_str(&format!(
            "            elements.push({});\n",
            decode_value(element_type, codec)
        ));
        out.push_str("        }\n");
        out.push_str(&format!("        value.{name} = elements;"));
        return;
    }

    match primitive(&field.network_type) {
        Some((_, reader_method, _)) => {
            out.push_str(&format!("value.{name} = reader.{reader_method}()?;"));
        }
        None => {
            let nested = codec_name(&field.network_type, codec);
            out.push_str(&format!("{nested}::decode(reader, &mut value.{name})?;"));
        }
    }
}

/// An expression producing one decoded array element. A primitive reads
/// straight through its `Reader` method; a nested model has no field to
/// decode in place (there is no element yet to reuse, unlike a bare nested
/// field - see [`decode_field`]), so it default-constructs one first. This
/// is the one place `Array<T>` requires something a bare `T` field does
/// not: `T: Default`, the same requirement every model in this project's
/// own fixtures already satisfies by deriving it.
fn decode_value(element_type: &str, codec: &str) -> String {
    match primitive(element_type) {
        Some((_, reader_method, _)) => format!("reader.{reader_method}()?"),
        None => {
            let nested = codec_name(element_type, codec);
            format!(
                "{{ let mut element = <{element_type} as ::core::default::Default>::default(); \
                 {nested}::decode(reader, &mut element)?; element }}"
            )
        }
    }
}

/// The generated type name: `DeviceState` + `edge` → `DeviceStateEdgeCodec`.
fn codec_name(model: &str, codec: &str) -> String {
    format!("{model}{}Codec", pascal_case(codec))
}

/// Looks a network type up in [`PRIMITIVES`].
fn primitive(network_type: &str) -> Option<(&'static str, &'static str, bool)> {
    PRIMITIVES
        .iter()
        .find(|(name, ..)| *name == network_type)
        .map(|(_, writer, reader, by_reference)| (*writer, *reader, *by_reference))
}
